# Site settings
title: Amay Advani
description: Website
baseurl: "/adva"
url: "http://amayadvani.github.io/adva"

# User settings
username: amayadvani
user_title: Amay Advani
email: amayadvani@gmail.com
github_username: amayadvani

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: https://github.com/amayadvani
      new_tab: true
      key_trigger: g
    - title: linkedin
      url: https://www.linkedin.com/in/amay-advani-67a56b264/
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: VASE
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara

exclude: ["package.json", "src", "node_modules"]
